services:
  # Backend API Service
  - type: web
    name: editorial-app-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DATABASE_URL
        fromDatabase:
          name: editorial-app-db
          property: connectionString
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: editorial-app-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: "/*"
        name: "X-Frame-Options"
        value: "DENY"
      - path: "/*"
        name: "X-Content-Type-Options"
        value: "nosniff"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: editorial-app-backend
          property: host
    autoDeploy: true

databases:
  - name: editorial-app-db
    databaseName: editorialdata
    user: editorialuser
    region: oregon
    plan: starter
    postgresMajorVersion: 15
