#!/bin/bash
# scripts/setup-render-supabase.sh - Configurar Render con Supabase

echo "🚀 Configurando Render con Supabase"
echo "===================================="
echo ""

echo "📋 Variables de entorno para Render Dashboard:"
echo ""

echo "🔧 BACKEND SERVICE (editorial-app-backend):"
echo "-------------------------------------------"
echo "NODE_ENV=production"
echo "PORT=10000"
echo "DATABASE_URL=postgresql://postgres:VqX2KgTvTZLrOWlq@db.ybnpusbnqlizaiqvztph.supabase.co:5432/postgres"
echo "DB_HOST=db.ybnpusbnqlizaiqvztph.supabase.co"
echo "DB_PORT=5432"
echo "DB_NAME=postgres"
echo "DB_USER=postgres"
echo "DB_PASSWORD=VqX2KgTvTZLrOWlq"
echo "JWT_SECRET=\$%^Tdasd9529841#\$&*9dascaseASDeqQQasdcEasdc\$##@33"
echo "JWT_EXPIRES_IN=24h"
echo "BCRYPT_ROUNDS=12"
echo "UPLOAD_MAX_SIZE=10485760"
echo "ALLOWED_FILE_TYPES=image/jpeg,image/png,image/gif,application/pdf"
echo "UPLOAD_FOLDER=uploads"
echo "RATE_LIMIT_WINDOW_MS=900000"
echo "RATE_LIMIT_MAX_REQUESTS=100"
echo ""

echo "🌐 FRONTEND SERVICE (editorial-app-frontend):"
echo "---------------------------------------------"
echo "NODE_ENV=production"
echo "VITE_API_URL=https://editorial-app-backend.onrender.com/api"
echo "VITE_API_TIMEOUT=10000"
echo ""

echo "📁 Archivos de configuración actualizados:"
echo "✅ .env.supabase - Variables para desarrollo/testing"
echo "✅ render-supabase.yaml - Configuración completa de Render"
echo ""

echo "🎯 Pasos para deployar en Render:"
echo ""
echo "1️⃣ Ve a tu dashboard de Render:"
echo "   👉 https://dashboard.render.com/"
echo ""
echo "2️⃣ Conecta tu repositorio GitHub:"
echo "   👉 New → Web Service"
echo "   👉 Connect GitHub: markitos002/editorial-app"
echo ""
echo "3️⃣ Configurar Backend Service:"
echo "   📝 Name: editorial-app-backend"
echo "   📂 Root Directory: backend"
echo "   🏗️  Build Command: npm install"
echo "   ▶️  Start Command: npm start"
echo "   🌍 Environment: Node"
echo "   💰 Plan: Free"
echo ""
echo "4️⃣ Agregar variables de entorno del backend (arriba) ⬆️"
echo ""
echo "5️⃣ Configurar Frontend Service:"
echo "   📝 Name: editorial-app-frontend"
echo "   📂 Root Directory: (vacío - raíz del repo)"
echo "   🏗️  Build Command: npm install && npm run build"
echo "   📁 Publish Directory: dist"
echo "   🌍 Environment: Static Site"
echo "   💰 Plan: Free"
echo ""
echo "6️⃣ Agregar variables de entorno del frontend (arriba) ⬆️"
echo ""

echo "⚡ Deploy automático:"
echo "   • Render detectará cambios en main"
echo "   • Deploy automático en cada push"
echo "   • URLs generadas automáticamente"
echo ""

echo "🔍 Verificación post-deploy:"
echo "   1. Backend health check: https://editorial-app-backend.onrender.com/health"
echo "   2. Frontend: https://editorial-app-frontend.onrender.com"
echo "   3. Verificar logs en Render Dashboard"
echo ""

echo "🎉 ¡Demo listo para el comité!"
